In [12]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filewarnings('ignore')

AttributeError: module 'warnings' has no attribute 'filewarnings'

In [43]:
df=sns.load_dataset("titanic")

In [44]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [45]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [47]:
df.drop(
    columns=['deck', 'embark_town', 'alive',
             'class', 'who', 'adult_male'],
    inplace=True,
    errors='ignore'
)

print(df.columns.tolist())

['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked', 'alone']

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    object
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object
 8   alone     891 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB

In [49]:
df["age"].fillna(df["age"].mean(),inplace=True)

/tmp/ipykernel_592/613402698.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["age"].fillna(df["age"].mean(),inplace=True)

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    object
 3   age       891 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object
 8   alone     891 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB

In [51]:
df.dropna(subset=["embarked"],inplace=True)

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  889 non-null    int64
 1   pclass    889 non-null    int64
 2   sex       889 non-null    object
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64
 5   parch     889 non-null    int64
 6   fare      889 non-null    float64
 7   embarked  889 non-null    object
 8   alone     889 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 63.4+ KB

In [53]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [54]:
df.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked  alone
0         0       3    male  22.0      1      0   7.2500        S  False
1         1       1  female  38.0      1      0  71.2833        C  False
2         1       3  female  26.0      0      0   7.9250        S   True
3         1       1  female  35.0      1      0  53.1000        S  False
4         0       3    male  35.0      0      0   8.0500        S   True

In [55]:
df['sex']=le.fit_transform(df['sex'])

In [56]:
df['embarked']=le.fit_transform(df['embarked'])

In [57]:
df=df.astype(int)
df.head()

   survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0         0       3    1   22      1      0     7         2      0
1         1       1    0   38      1      0    71         0      0
2         1       3    0   26      0      0     7         2      1
3         1       1    0   35      1      0    53         2      0
4         0       3    1   35      0      0     8         2      1

In [58]:
x=df.drop("survived",axis=1)
y=df['survived']

In [59]:
from sklearn.model_selection import train_test_split

In [60]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [61]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [62]:
y_pred=model.predict(x_test)

In [63]:
y_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0])

In [64]:
y_test

281    0
435    1
39     1
418    0
585    1
      ..
711    0
840    0
381    1
141    1
174    0
Name: survived, Length: 294, dtype: int64

In [65]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [66]:
accuracy_score(y_test,y_pred)

0.8163265306122449

In [67]:
confusion_matrix(y_test,y_pred)

array([[157,  27],
       [ 27,  83]])

In [68]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.85      0.85      0.85       184
           1       0.75      0.75      0.75       110

    accuracy                           0.82       294
   macro avg       0.80      0.80      0.80       294
weighted avg       0.82      0.82      0.82       294

In [69]:
df

     survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0           0       3    1   22      1      0     7         2      0
1           1       1    0   38      1      0    71         0      0
2           1       3    0   26      0      0     7         2      1
3           1       1    0   35      1      0    53         2      0
4           0       3    1   35      0      0     8         2      1
..        ...     ...  ...  ...    ...    ...   ...       ...    ...
886         0       2    1   27      0      0    13         2      1
887         1       1    0   19      0      0    30         2      1
888         0       3    0   29      1      2    23         2      0
889         1       1    1   26      0      0    30         0      1
890         0       3    1   32      0      0     7         1      1

[889 rows x 9 columns]

In [70]:
x_test

     pclass  sex  age  sibsp  parch  fare  embarked  alone
281       3    1   28      0      0     7         2      1
435       1    0   14      1      2   120         2      0
39        3    0   14      1      0    11         0      0
418       2    1   30      0      0    13         2      1
585       1    0   18      0      2    79         2      0
..      ...  ...  ...    ...    ...   ...       ...    ...
711       1    1   29      0      0    26         2      1
840       3    1   20      0      0     7         2      1
381       3    0    1      0      2    15         0      0
141       3    0   22      0      0     7         2      1
174       1    1   56      0      0    30         0      1

[294 rows x 8 columns]

In [71]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [72]:
xtrain=sc.fit_transform(x_train)
xtrain

array([[-1.60124536,  0.71693438,  1.82943665, ...,  0.36229213,
         0.58362385,  0.82798092],
       [-0.39524411, -1.39482779,  0.3172955 , ..., -0.37587359,
         0.58362385,  0.82798092],
       [-1.60124536,  0.71693438, -1.95091623, ...,  0.94505454,
         0.58362385, -1.2077573 ],
       ...,
       [-1.60124536, -1.39482779,  1.37579431, ..., -0.14276863,
         0.58362385,  0.82798092],
       [ 0.81075714, -1.39482779, -0.66559625, ...,  0.03206009,
         0.58362385, -1.2077573 ],
       [ 0.81075714,  0.71693438,  0.24168844, ..., -0.47300066,
         0.58362385,  0.82798092]])

In [73]:
xtest=sc.transform(x_test)
xtest

array([[ 0.81075714,  0.71693438, -0.13634685, ..., -0.49242607,
         0.58362385,  0.82798092],
       [-1.60124536, -1.39482779, -1.19484565, ...,  1.70264567,
         0.58362385, -1.2077573 ],
       [ 0.81075714, -1.39482779, -1.19484565, ..., -0.41472442,
        -1.96037756, -1.2077573 ],
       ...,
       [ 0.81075714, -1.39482779, -2.1777374 , ..., -0.33702276,
        -1.96037756, -1.2077573 ],
       [ 0.81075714, -1.39482779, -0.58998919, ..., -0.49242607,
         0.58362385,  0.82798092],
       [-1.60124536,  0.71693438,  1.98065077, ..., -0.04564156,
        -1.96037756,  0.82798092]])

In [74]:
from sklearn.neighbors import KNeighborsClassifier

In [75]:
knnmodel=KNeighborsClassifier(n_neighbors=5)

In [76]:
knnmodel.fit(xtrain,y_train)

KNeighborsClassifier()

In [77]:
ypred_knn=knnmodel.predict(xtest)

In [78]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
accuracy_score(y_test,ypred_knn)

0.8197278911564626

In [79]:
confusion_matrix(y_test,ypred_knn)

array([[161,  23],
       [ 30,  80]])

In [80]:
print(classification_report(y_test,ypred_knn))

              precision    recall  f1-score   support

           0       0.84      0.88      0.86       184
           1       0.78      0.73      0.75       110

    accuracy                           0.82       294
   macro avg       0.81      0.80      0.80       294
weighted avg       0.82      0.82      0.82       294

In [81]:
x_test

     pclass  sex  age  sibsp  parch  fare  embarked  alone
281       3    1   28      0      0     7         2      1
435       1    0   14      1      2   120         2      0
39        3    0   14      1      0    11         0      0
418       2    1   30      0      0    13         2      1
585       1    0   18      0      2    79         2      0
..      ...  ...  ...    ...    ...   ...       ...    ...
711       1    1   29      0      0    26         2      1
840       3    1   20      0      0     7         2      1
381       3    0    1      0      2    15         0      0
141       3    0   22      0      0     7         2      1
174       1    1   56      0      0    30         0      1

[294 rows x 8 columns]

In [82]:
x_train

     pclass  sex  age  sibsp  parch  fare  embarked  alone
6         1    1   54      0      0    51         2      1
576       2    0   34      0      0    13         2      1
445       1    1    4      0      2    81         2      0
74        3    1   32      0      0    56         2      1
670       2    0   40      1      1    39         2      0
..      ...  ...  ...    ...    ...   ...       ...    ...
107       3    1   29      0      0     7         2      1
271       3    1   25      0      0     0         2      1
862       1    0   48      0      0    25         2      1
436       3    0   21      2      2    34         2      0
103       3    1   33      0      0     8         2      1

[595 rows x 8 columns]

In [83]:
xtrain

array([[-1.60124536,  0.71693438,  1.82943665, ...,  0.36229213,
         0.58362385,  0.82798092],
       [-0.39524411, -1.39482779,  0.3172955 , ..., -0.37587359,
         0.58362385,  0.82798092],
       [-1.60124536,  0.71693438, -1.95091623, ...,  0.94505454,
         0.58362385, -1.2077573 ],
       ...,
       [-1.60124536, -1.39482779,  1.37579431, ..., -0.14276863,
         0.58362385,  0.82798092],
       [ 0.81075714, -1.39482779, -0.66559625, ...,  0.03206009,
         0.58362385, -1.2077573 ],
       [ 0.81075714,  0.71693438,  0.24168844, ..., -0.47300066,
         0.58362385,  0.82798092]])

In [84]:
from sklearn.naive_bayes import GaussianNB

In [85]:
modelnb=GaussianNB()

In [86]:
x_test

     pclass  sex  age  sibsp  parch  fare  embarked  alone
281       3    1   28      0      0     7         2      1
435       1    0   14      1      2   120         2      0
39        3    0   14      1      0    11         0      0
418       2    1   30      0      0    13         2      1
585       1    0   18      0      2    79         2      0
..      ...  ...  ...    ...    ...   ...       ...    ...
711       1    1   29      0      0    26         2      1
840       3    1   20      0      0     7         2      1
381       3    0    1      0      2    15         0      0
141       3    0   22      0      0     7         2      1
174       1    1   56      0      0    30         0      1

[294 rows x 8 columns]

In [87]:
modelnb.fit(xtrain,y_train)

GaussianNB()

In [88]:
y_pred_nb=modelnb.predict(xtest)

In [89]:
y_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0])

In [90]:
y_test

281    0
435    1
39     1
418    0
585    1
      ..
711    0
840    0
381    1
141    1
174    0
Name: survived, Length: 294, dtype: int64

In [91]:
accuracy_score(y_test,y_pred_nb)

0.7789115646258503

In [92]:
print(classification_report(y_test,y_pred_nb))

              precision    recall  f1-score   support

           0       0.85      0.79      0.82       184
           1       0.68      0.76      0.72       110

    accuracy                           0.78       294
   macro avg       0.77      0.78      0.77       294
weighted avg       0.79      0.78      0.78       294

In [93]:
confusion_matrix(y_test,y_pred_nb)

array([[145,  39],
       [ 26,  84]])

In [94]:
from sklearn.tree import DecisionTreeClassifier

In [95]:
modeldt=DecisionTreeClassifier(random_state=42)

In [96]:
modeldt.fit(xtrain,y_train)

DecisionTreeClassifier(random_state=42)

In [97]:
y_pred_dt=modeldt.predict(xtest)
y_pred_dt

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0])

In [98]:
accuracy_score(y_test,y_pred_dt)

0.7857142857142857

In [99]:
confusion_matrix(y_test,y_pred_dt)

array([[155,  29],
       [ 34,  76]])

In [100]:
print(classification_report(y_test,y_pred_dt))

              precision    recall  f1-score   support

           0       0.82      0.84      0.83       184
           1       0.72      0.69      0.71       110

    accuracy                           0.79       294
   macro avg       0.77      0.77      0.77       294
weighted avg       0.78      0.79      0.78       294

In [101]:
from sklearn.svm import SVC

In [102]:
modelsvm=SVC(kernel='rbf')

In [103]:
modelsvm.fit(xtrain,y_train)

SVC()

In [104]:
y_predsvc=modelsvm.predict(xtest)

In [105]:
accuracy_score(y_test,y_predsvc)

0.8231292517006803

In [106]:
confusion_matrix(y_test,y_predsvc)

array([[160,  24],
       [ 28,  82]])

In [107]:
print(classification_report(y_test,y_predsvc))

              precision    recall  f1-score   support

           0       0.85      0.87      0.86       184
           1       0.77      0.75      0.76       110

    accuracy                           0.82       294
   macro avg       0.81      0.81      0.81       294
weighted avg       0.82      0.82      0.82       294

CROSS VALIDATION

In [108]:
df

     survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0           0       3    1   22      1      0     7         2      0
1           1       1    0   38      1      0    71         0      0
2           1       3    0   26      0      0     7         2      1
3           1       1    0   35      1      0    53         2      0
4           0       3    1   35      0      0     8         2      1
..        ...     ...  ...  ...    ...    ...   ...       ...    ...
886         0       2    1   27      0      0    13         2      1
887         1       1    0   19      0      0    30         2      1
888         0       3    0   29      1      2    23         2      0
889         1       1    1   26      0      0    30         0      1
890         0       3    1   32      0      0     7         1      1

[889 rows x 9 columns]

In [109]:
x=df.drop('survived',axis=1)
y=df['survived']

In [110]:
from sklearn.model_selection import cross_val_score

In [111]:
scaler=StandardScaler()
x_scaled=scaler.fit_transform(x)

In [112]:
scores=cross_val_score(modelsvm,x_scaled,y,cv=5,scoring='accuracy')

In [113]:
print(scores)

[0.83146067 0.82022472 0.81460674 0.80898876 0.86440678]

In [114]:
print(scores.mean())

0.8279375357074844