In [88]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import StackingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,classification_report
import seaborn as sns

In [89]:
df=sns.load_dataset('iris')

In [90]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [91]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [92]:
X=df.drop('species',axis=1)
y=df["species"]

In [93]:
X

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [94]:
y

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [95]:
le=LabelEncoder()
y_encoded=le.fit_transform(y)

In [96]:
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2,
random_state=42,stratify=y_encoded)

In [97]:
base_learner=[
    ('dt' ,DecisionTreeClassifier(random_state=42)),
    ('svc',SVC(probability=True,kernel='rbf',random_state=42)),
    ('lr',LogisticRegression(max_iter=1000))
]

In [98]:
meta_learner=LogisticRegression(max_iter=1000)

In [99]:
stacking_clf=StackingClassifier(
    estimators=base_learner,
    final_estimator=meta_learner,
    cv=5
)

In [100]:
stacking_clf.fit(X_train,y_train)

StackingClassifier(cv=5,
                   estimators=[('dt', DecisionTreeClassifier(random_state=42)),
                               ('svc', SVC(probability=True, random_state=42)),
                               ('lr', LogisticRegression(max_iter=1000))],
                   final_estimator=LogisticRegression(max_iter=1000))

In [101]:
y_pred=stacking_clf.predict(X_test)
y_pred

array([0, 2, 1, 1, 0, 1, 0, 0, 2, 1, 2, 2, 2, 1, 0, 0, 0, 1, 1, 2, 0, 2,
       1, 2, 2, 2, 1, 0, 2, 0])

In [102]:
accuracy=accuracy_score(y_test,y_pred)

In [103]:
accuracy

0.9666666666666667

In [104]:
from sklearn.ensemble import RandomForestClassifier

In [105]:
rf_model=RandomForestClassifier(
    n_estimators=100,max_depth=None,
    random_state=42
)

In [106]:
rf_model.fit(X_train,y_train)

RandomForestClassifier(random_state=42)

In [107]:
y_pred=rf_model.predict(X_test)

In [108]:
accuracy=accuracy_score(y_test,y_pred)

In [109]:
accuracy

0.9

In [110]:
from sklearn.ensemble import AdaBoostClassifier,GradientBoostingClassifier

In [111]:
from xgboost import XGBClassifier

In [112]:
ada_model=AdaBoostClassifier(
    n_estimators=100,random_state=42
)

In [113]:
ada_model.fit(X_train,y_train)

AdaBoostClassifier(n_estimators=100, random_state=42)

In [114]:
y_pred=ada_model.predict(X_test)

In [115]:
ac=accuracy_score(y_test,y_pred)

In [116]:
ac

0.9333333333333333

In [117]:
gb_model=GradientBoostingClassifier(
    n_estimators=100,random_state=42
)

In [118]:
gb_model.fit(X_train,y_train)

GradientBoostingClassifier(random_state=42)

In [119]:
y_pred=gb_model.predict(X_test)

In [120]:
acuracy=accuracy_score(y_test,y_pred)

In [121]:
acuracy

0.9666666666666667

In [122]:
xgboost_model=XGBClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    use_label_encoder=False,
    eval_matrics='mlogloss',
    random_state=42
)

In [123]:
xgboost_model.fit(X_train,y_train)

/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [09:52:34] WARNING: /__w/xgboost/xgboost/src/learner.cc:794:
Parameters: { "eval_matrics", "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_matrics='mlogloss',
              eval_metric=None, feature_types=None, feature_weights=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None, ...)

In [124]:
y_pred=xgboost_model.predict(X_test)

In [125]:
y_pred

array([0, 2, 1, 1, 0, 1, 0, 0, 2, 1, 2, 2, 2, 1, 0, 0, 0, 1, 1, 1, 0, 2,
       1, 2, 2, 2, 1, 0, 2, 0])

In [126]:
accuracy=accuracy_score(y_test,y_pred)

In [127]:
accuracy

0.9333333333333333